package net.superblaubeere27.masxinlingvaj.compiler.newAST.locals;

import net.superblaubeere27.masxinlingvaj.compiler.newAST.ImmType;
import net.superblaubeere27.masxinlingvaj.compiler.newAST.Local;

import java.util.Objects;

/**
 * A local generated by the IR generator
 */
public class SyntheticLocal extends Local {
    private final int idx;
    private final ImmType type;

    public SyntheticLocal(int idx, ImmType type) {
        this.idx = idx;
        this.type = type;
    }


    @Override
    public ImmType getType() {
        return this.type;
    }

    @Override
    public boolean isSSA() {
        return false;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SyntheticLocal that = (SyntheticLocal) o;
        return idx == that.idx && type == that.type;
    }

    @Override
    public int hashCode() {
        return Objects.hash(idx, type);
    }

    @Override
    public String toString() {
        return "%synth" + this.idx + this.type.getAssociatedCharacter();
    }
}
