package net.superblaubeere27.masxinlingvaj.compiler.jni;

import net.superblaubeere27.masxinlingvaj.compiler.TranslatedMethod;
import org.bytedeco.javacpp.PointerPointer;
import org.bytedeco.llvm.LLVM.*;
import org.bytedeco.llvm.global.LLVM;

import java.util.Arrays;
import java.util.Locale;

import static org.bytedeco.llvm.global.LLVM.*;

public class JNIEnv {
    private final LLVMTypeRef type;

    JNIEnv(LLVMContextRef context) {
        var jniInterfaceStruct = LLVMStructCreateNamed(context, "struct.JNINativeInterface");

        LLVMTypeRef[] array = Arrays.stream(JNIEnvMethod.values()).map(x -> x.llvmType).toArray(LLVMTypeRef[]::new);

        LLVMStructSetBody(jniInterfaceStruct, new PointerPointer<>(array), array.length, 0);

        var envType = LLVMStructCreateNamed(context, "struct.JNIEnv");

        LLVMStructSetBody(envType,
                new PointerPointer<>(new LLVMTypeRef[]{LLVMPointerType(jniInterfaceStruct, 0)}),
                1,
                0);

        this.type = envType;
    }

    private static LLVMTypeRef functionType(LLVMTypeRef returnType, LLVMTypeRef[] paramTypes, boolean vararg) {
        return LLVMPointerType(LLVM.LLVMFunctionType(returnType,
                new PointerPointer<>(paramTypes),
                paramTypes.length,
                vararg ? 1 : 0), 0);
    }

    public LLVMTypeRef getType() {
        return type;
    }

    public LLVMValueRef callEnvironmentMethod(TranslatedMethod translatedMethod, LLVMValueRef envPtr, JNIEnvMethod method, LLVMValueRef... params) {
        return callEnvironmentMethod(envPtr, method, translatedMethod.getLlvmBuilder(), translatedMethod.getJniFunctionTable(), params);
    }

    public LLVMValueRef callEnvironmentMethod(LLVMValueRef envPtr, JNIEnvMethod method, LLVMBuilderRef builder, LLVMValueRef functionTable, LLVMValueRef... params) {
        var methodName = method.toString().toLowerCase(Locale.ROOT);
        var function_ptr = LLVMBuildLoad(builder,
                LLVMBuildStructGEP(builder, functionTable, method.ordinal(), ""),
                methodName + "*");

        var param_array = new LLVMValueRef[params.length + 1];

        param_array[0] = LLVMBuildBitCast(builder, envPtr, JNIType.OBJECT.getLLVMType(), "");

        System.arraycopy(params, 0, param_array, 1, params.length);

        String name;

        // Because void functions cannot have names...
        if (LLVMGetTypeKind(LLVM.LLVMGetReturnType(LLVMGetElementType(method.llvmType))) == LLVMVoidTypeKind) {
            name = "";
        } else {
            name = "call_" + methodName;
        }

        var call = LLVMBuildCall(builder, function_ptr, new PointerPointer<>(param_array), param_array.length, name);

        if (method.sideEffectType.attributeRef != null) {
            LLVM.LLVMAddCallSiteAttribute(call, LLVMAttributeFunctionIndex, method.sideEffectType.attributeRef);
        }

//        LLVM.LLVMSetInstructionCallConv(call, LLVMX86StdcallCallConv);

        return call;
    }

    public enum JNIEnvMethod {
        UNNAMED0(SideEffectType.NORMAL, LLVMPointerType(LLVMInt8Type(), 0)),
        UNNAMED1(SideEffectType.NORMAL, LLVMPointerType(LLVMInt8Type(), 0)),
        UNNAMED2(SideEffectType.NORMAL, LLVMPointerType(LLVMInt8Type(), 0)),
        UNNAMED3(SideEffectType.NORMAL, LLVMPointerType(LLVMInt8Type(), 0)),
        GetVersion(SideEffectType.READ_NONE,
                functionType(JNIType.INT.getLLVMType(), new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0)}, false)),
        DefineClass(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BYTE.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        FindClass(SideEffectType.READ_NONE,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        FromReflectedMethod(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        FromReflectedField(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        ToReflectedMethod(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.BOOLEAN.getLLVMType()},
                        false)),
        GetSuperclass(SideEffectType.READ_NONE,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        IsAssignableFrom(SideEffectType.READ_NONE,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        ToReflectedField(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.BOOLEAN.getLLVMType()},
                        false)),
        Throw(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        ThrowNew(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        ExceptionOccurred(SideEffectType.READ_ONLY,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        ExceptionDescribe(SideEffectType.NORMAL,
                functionType(LLVMVoidType(), new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0)}, false)),
        ExceptionClear(SideEffectType.NORMAL,
                functionType(LLVMVoidType(), new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0)}, false)),
        FatalError(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        PushLocalFrame(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        PopLocalFrame(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        NewGlobalRef(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        DeleteGlobalRef(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        DeleteLocalRef(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        IsSameObject(SideEffectType.READ_NONE,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        NewLocalRef(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        EnsureLocalCapacity(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        AllocObject(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        NewObject(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        NewObjectV(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        NewObjectA(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        GetObjectClass(SideEffectType.READ_NONE,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        IsInstanceOf(SideEffectType.READ_NONE,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetMethodID(SideEffectType.READ_NONE,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallObjectMethod(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallObjectMethodV(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallObjectMethodA(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallBooleanMethod(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallBooleanMethodV(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallBooleanMethodA(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallByteMethod(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallByteMethodV(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallByteMethodA(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallCharMethod(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallCharMethodV(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallCharMethodA(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallShortMethod(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallShortMethodV(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallShortMethodA(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallIntMethod(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallIntMethodV(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallIntMethodA(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallLongMethod(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallLongMethodV(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallLongMethodA(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallFloatMethod(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallFloatMethodV(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallFloatMethodA(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallDoubleMethod(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallDoubleMethodV(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallDoubleMethodA(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallVoidMethod(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallVoidMethodV(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallVoidMethodA(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualObjectMethod(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualObjectMethodV(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualObjectMethodA(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualBooleanMethod(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualBooleanMethodV(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualBooleanMethodA(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualByteMethod(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualByteMethodV(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualByteMethodA(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualCharMethod(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualCharMethodV(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualCharMethodA(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualShortMethod(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualShortMethodV(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualShortMethodA(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualIntMethod(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualIntMethodV(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualIntMethodA(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualLongMethod(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualLongMethodV(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualLongMethodA(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualFloatMethod(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualFloatMethodV(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualFloatMethodA(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualDoubleMethod(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualDoubleMethodV(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualDoubleMethodA(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualVoidMethod(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallNonvirtualVoidMethodV(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallNonvirtualVoidMethodA(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        GetFieldID(SideEffectType.READ_NONE,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        GetObjectField(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetBooleanField(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetByteField(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetCharField(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetShortField(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetIntField(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetLongField(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetFloatField(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetDoubleField(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        SetObjectField(SideEffectType.NORMAL,
                       functionType(LLVMVoidType(),
                                    new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                      0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                                    false)),
        SetBooleanField(SideEffectType.NORMAL,
                        functionType(LLVMVoidType(),
                                     new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                       0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.BOOLEAN.getLLVMType()},
                                     false)),
        SetByteField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.BYTE.getLLVMType()},
                        false)),
        SetCharField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.CHAR.getLLVMType()},
                        false)),
        SetShortField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.SHORT.getLLVMType()},
                        false)),
        SetIntField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType()},
                        false)),
        SetLongField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.LONG.getLLVMType()},
                        false)),
        SetFloatField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.FLOAT.getLLVMType()},
                        false)),
        SetDoubleField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.DOUBLE.getLLVMType()},
                        false)),
        GetStaticMethodID(SideEffectType.READ_NONE,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticObjectMethod(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticObjectMethodV(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticObjectMethodA(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticBooleanMethod(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticBooleanMethodV(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticBooleanMethodA(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticByteMethod(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticByteMethodV(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticByteMethodA(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticCharMethod(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticCharMethodV(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticCharMethodA(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticShortMethod(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticShortMethodV(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticShortMethodA(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticIntMethod(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticIntMethodV(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticIntMethodA(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticLongMethod(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticLongMethodV(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticLongMethodA(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticFloatMethod(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticFloatMethodV(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticFloatMethodA(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticDoubleMethod(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticDoubleMethodV(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticDoubleMethodA(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticVoidMethod(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        true)),
        CallStaticVoidMethodV(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        CallStaticVoidMethodA(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        GetStaticFieldID(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(
                                LLVMInt8Type(),
                                0)},
                        false)),
        GetStaticObjectField(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticBooleanField(SideEffectType.NORMAL,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticByteField(SideEffectType.NORMAL,
                functionType(JNIType.BYTE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticCharField(SideEffectType.NORMAL,
                functionType(JNIType.CHAR.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticShortField(SideEffectType.NORMAL,
                functionType(JNIType.SHORT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticIntField(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticLongField(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticFloatField(SideEffectType.NORMAL,
                functionType(JNIType.FLOAT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStaticDoubleField(SideEffectType.NORMAL,
                functionType(JNIType.DOUBLE.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        SetStaticObjectField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        SetStaticBooleanField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.BOOLEAN.getLLVMType()},
                        false)),
        SetStaticByteField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.BYTE.getLLVMType()},
                        false)),
        SetStaticCharField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.CHAR.getLLVMType()},
                        false)),
        SetStaticShortField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.SHORT.getLLVMType()},
                        false)),
        SetStaticIntField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType()},
                        false)),
        SetStaticLongField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.LONG.getLLVMType()},
                        false)),
        SetStaticFloatField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.FLOAT.getLLVMType()},
                        false)),
        SetStaticDoubleField(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.DOUBLE.getLLVMType()},
                        false)),
        NewString(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), LLVMPointerType(JNIType.CHAR.getLLVMType(), 0), JNIType.INT.getLLVMType()},
                        false)),
        GetStringLength(SideEffectType.READ_NONE,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStringChars(SideEffectType.READ_NONE,
                functionType(LLVMPointerType(JNIType.CHAR.getLLVMType(), 0),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BOOLEAN.getLLVMType(), 0)},
                        false)),
        ReleaseStringChars(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.CHAR.getLLVMType(), 0)},
                        false)),
        NewStringUTF(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        GetStringUTFLength(SideEffectType.READ_NONE,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetStringUTFChars(SideEffectType.READ_NONE,
                functionType(LLVMPointerType(LLVMInt8Type(), 0),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BOOLEAN.getLLVMType(), 0)},
                        false)),
        ReleaseStringUTFChars(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        GetArrayLength(SideEffectType.READ_NONE,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        NewObjectArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.INT.getLLVMType(), JNIType.OBJECT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetObjectArrayElement(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType()},
                        false)),
        SetObjectArrayElement(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.OBJECT.getLLVMType()},
                        false)),
        NewBooleanArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewByteArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewCharArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewShortArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewIntArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewLongArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewFloatArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        NewDoubleArray(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.INT.getLLVMType()},
                        false)),
        GetBooleanArrayElements(SideEffectType.ARG_MEM_ONLY,
                                functionType(LLVMPointerType(JNIType.BOOLEAN.getLLVMType(), 0),
                                             new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                               0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                     JNIType.BOOLEAN.getLLVMType(),
                                                     0)},
                                             false)),
        GetByteArrayElements(SideEffectType.ARG_MEM_ONLY,
                             functionType(LLVMPointerType(JNIType.BYTE.getLLVMType(), 0),
                                          new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                            0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                  JNIType.BOOLEAN.getLLVMType(),
                                                  0)},
                                          false)),
        GetCharArrayElements(SideEffectType.ARG_MEM_ONLY,
                             functionType(LLVMPointerType(JNIType.CHAR.getLLVMType(), 0),
                                          new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                            0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                  JNIType.BOOLEAN.getLLVMType(),
                                                  0)},
                                          false)),
        GetShortArrayElements(SideEffectType.ARG_MEM_ONLY,
                              functionType(LLVMPointerType(JNIType.SHORT.getLLVMType(), 0),
                                           new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                             0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                   JNIType.BOOLEAN.getLLVMType(),
                                                   0)},
                                           false)),
        GetIntArrayElements(SideEffectType.ARG_MEM_ONLY,
                            functionType(LLVMPointerType(JNIType.INT.getLLVMType(), 0),
                                         new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                           0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                 JNIType.BOOLEAN.getLLVMType(),
                                                 0)},
                                         false)),
        GetLongArrayElements(SideEffectType.ARG_MEM_ONLY,
                             functionType(LLVMPointerType(JNIType.LONG.getLLVMType(), 0),
                                          new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                            0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                  JNIType.BOOLEAN.getLLVMType(),
                                                  0)},
                                          false)),
        GetFloatArrayElements(SideEffectType.ARG_MEM_ONLY,
                              functionType(LLVMPointerType(JNIType.FLOAT.getLLVMType(), 0),
                                           new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                             0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                   JNIType.BOOLEAN.getLLVMType(),
                                                   0)},
                                           false)),
        GetDoubleArrayElements(SideEffectType.ARG_MEM_ONLY,
                               functionType(LLVMPointerType(JNIType.DOUBLE.getLLVMType(), 0),
                                            new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                              0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(
                                                    JNIType.BOOLEAN.getLLVMType(),
                                                    0)},
                                            false)),
        ReleaseBooleanArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BOOLEAN.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseByteArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BYTE.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseCharArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.CHAR.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseShortArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.SHORT.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseIntArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.INT.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseLongArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.LONG.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseFloatArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.FLOAT.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        ReleaseDoubleArrayElements(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.DOUBLE.getLLVMType(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        GetBooleanArrayRegion(SideEffectType.ARG_MEM_ONLY,
                              functionType(LLVMVoidType(),
                                           new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                             0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                   JNIType.BOOLEAN.getLLVMType(),
                                                   0)},
                                           false)),
        GetByteArrayRegion(SideEffectType.ARG_MEM_ONLY,
                           functionType(LLVMVoidType(),
                                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                          0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                JNIType.BYTE.getLLVMType(),
                                                0)},
                                        false)),
        GetCharArrayRegion(SideEffectType.ARG_MEM_ONLY,
                           functionType(LLVMVoidType(),
                                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                          0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                JNIType.CHAR.getLLVMType(),
                                                0)},
                                        false)),
        GetShortArrayRegion(SideEffectType.ARG_MEM_ONLY,
                            functionType(LLVMVoidType(),
                                         new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                           0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                 JNIType.SHORT.getLLVMType(),
                                                 0)},
                                         false)),
        GetIntArrayRegion(SideEffectType.ARG_MEM_ONLY,
                          functionType(LLVMVoidType(),
                                       new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                         0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                               JNIType.INT.getLLVMType(),
                                               0)},
                                       false)),
        GetLongArrayRegion(SideEffectType.ARG_MEM_ONLY,
                           functionType(LLVMVoidType(),
                                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                          0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                JNIType.LONG.getLLVMType(),
                                                0)},
                                        false)),
        GetFloatArrayRegion(SideEffectType.ARG_MEM_ONLY,
                            functionType(LLVMVoidType(),
                                         new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                           0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                 JNIType.FLOAT.getLLVMType(),
                                                 0)},
                                         false)),
        GetDoubleArrayRegion(SideEffectType.ARG_MEM_ONLY,
                             functionType(LLVMVoidType(),
                                          new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                            0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                                  JNIType.DOUBLE.getLLVMType(),
                                                  0)},
                                          false)),
        SetBooleanArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.BOOLEAN.getLLVMType(),
                                0)},
                        false)),
        SetByteArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.BYTE.getLLVMType(),
                                0)},
                        false)),
        SetCharArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.CHAR.getLLVMType(),
                                0)},
                        false)),
        SetShortArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.SHORT.getLLVMType(),
                                0)},
                        false)),
        SetIntArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.INT.getLLVMType(),
                                0)},
                        false)),
        SetLongArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.LONG.getLLVMType(),
                                0)},
                        false)),
        SetFloatArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.FLOAT.getLLVMType(),
                                0)},
                        false)),
        SetDoubleArrayRegion(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                JNIType.DOUBLE.getLLVMType(),
                                0)},
                        false)),
        RegisterNatives(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        UnregisterNatives(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        MonitorEnter(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        MonitorExit(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetJavaVM(SideEffectType.NORMAL,
                functionType(JNIType.INT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(LLVMPointerType(
                                LLVMInt8Type(),
                                0), 0)},
                        false)),
        GetStringRegion(SideEffectType.ARG_MEM_ONLY,
                        functionType(LLVMVoidType(),
                                     new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                       0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType(), LLVMPointerType(
                                             JNIType.CHAR.getLLVMType(),
                                             0)},
                                     false)),
        GetStringUTFRegion(SideEffectType.ARG_MEM_ONLY,
                           functionType(LLVMVoidType(),
                                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                                                          0), JNIType.OBJECT.getLLVMType(), JNIType.INT.getLLVMType(), JNIType.INT.getLLVMType()},
                                        false)),
        GetPrimitiveArrayCritical(SideEffectType.NORMAL,
                functionType(LLVMPointerType(LLVMInt8Type(), 0),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BOOLEAN.getLLVMType(), 0)},
                        false)),
        ReleasePrimitiveArrayCritical(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.INT.getLLVMType()},
                        false)),
        GetStringCritical(SideEffectType.NORMAL,
                functionType(LLVMPointerType(JNIType.CHAR.getLLVMType(), 0),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.BOOLEAN.getLLVMType(), 0)},
                        false)),
        ReleaseStringCritical(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.OBJECT.getLLVMType(), LLVMPointerType(JNIType.CHAR.getLLVMType(), 0)},
                        false)),
        NewWeakGlobalRef(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        DeleteWeakGlobalRef(SideEffectType.NORMAL,
                functionType(LLVMVoidType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        ExceptionCheck(SideEffectType.READ_ONLY,
                functionType(JNIType.BOOLEAN.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0)},
                        false)),
        NewDirectByteBuffer(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), LLVMPointerType(LLVMInt8Type(),
                                0), JNIType.LONG.getLLVMType()},
                        false)),
        GetDirectBufferAddress(SideEffectType.NORMAL,
                functionType(LLVMPointerType(LLVMInt8Type(), 0),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetDirectBufferCapacity(SideEffectType.NORMAL,
                functionType(JNIType.LONG.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false)),
        GetObjectRefType(SideEffectType.NORMAL,
                functionType(JNIType.OBJECT.getLLVMType(),
                        new LLVMTypeRef[]{LLVMPointerType(LLVMInt8Type(), 0), JNIType.OBJECT.getLLVMType()},
                        false));

        private final SideEffectType sideEffectType;
        private final LLVMTypeRef llvmType;

        JNIEnvMethod(SideEffectType sideEffectType, LLVMTypeRef llvmType) {
            this.sideEffectType = sideEffectType;
            this.llvmType = llvmType;
        }
    }


    public enum SideEffectType {
        NORMAL(null), READ_ONLY("readonly"), ARG_MEM_ONLY("argmemonly"), WRITE_ONLY("writeonly"), READ_NONE("readnone");

        private final LLVMAttributeRef attributeRef;

        SideEffectType(String attributeName) {
            if (attributeName == null) {
                this.attributeRef = null;
            } else {
                this.attributeRef = LLVM.LLVMCreateEnumAttribute(LLVM.LLVMGetGlobalContext(),
                                                                 LLVM.LLVMGetEnumAttributeKindForName(attributeName,
                                                                                                      attributeName.length()),
                                                                 0);
            }
        }
    }

}
